# 
# Bases de Dados 2020/2021
# Aulas Práticas
#


version: '3'

services:
  db_fichas:
    build: ./postgresql
    container_name: db_fichas
    expose:
      - "5432"
    ports:
      - "5432:5432"

  pgadmin:
    build: ./pgadmin
    depends_on:
      - db_fichas
    container_name: pgadm_fichas
    expose:
      - "5555"
    ports:
      - "5555:80"